# Generated by Django 4.0.3 on 2022-04-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_choice_remove_question_answer_text_delete_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='selected_ids',
            field=models.IntegerField(default=0),
        ),
    ]
