# Generated by Django 4.0.3 on 2022-04-09 21:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0006_alter_submission_selected_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='selected_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
